### ISSUE TITLE
transfer the latest Bridges flow from zeplin to figma

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/beam-bridge-ethapp#10]
We need to transfer the latest Bridges design from Zeplin to Figma. We will continue to work with you at the Bridge.

Here is Bridges new page in Figma
https://www.figma.com/file/LteN0e1tygpYgzjQmCPZCu/Bridges-Landing?node-id=3%3A2

Here is the latest Bridges flow (from the right).
https://www.figma.com/file/oey7NPfRs6UHXdF7vHQQL5/Bridges-flows?node-id=0%3A1
https://app.zeplin.io/project/60cb0b7ebec4ebbd1fdd7f4f

<img width="871" alt="Снимок экрана 2022-05-11 в 10 42 58" src="https://user-images.githubusercontent.com/94360080/167795941-dca85a2a-83b3-442c-aad2-046cc0edda3a.png">

**Comment by dariatarakanova** [comment]
Done https://www.figma.com/file/LteN0e1tygpYgzjQmCPZCu/Bridges-Landing?node-id=55%3A2

**Comment by dariatarakanova** [comment]
Done https://www.figma.com/file/LteN0e1tygpYgzjQmCPZCu/Bridges-Landing?node-id=55%3A2
