### ISSUE TITLE
Bridges. Main screen (before connecting wallet). General

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/beam-bridge-ethapp#2]
https://zpl.io/awdoOlN
1. Change header from "ETH to BEAM Bridge" into "Etherium to Beam Bridge"
<img width="904" alt="Screenshot at Dec 08 13-33-27" src="https://user-images.githubusercontent.com/7249484/145154041-b190f975-9c2c-46ae-b722-f6127d68abe7.png">

2. Change the description on the main screen (old "Send funds through BEAM Smart Contract", new "Transfer ETH, wBTC, DAI and USDT. More tokens are coming soon!")
<img width="902" alt="Screenshot at Dec 08 13-33-43" src="https://user-images.githubusercontent.com/7249484/145154069-418f2fd9-237a-4fcf-afc6-779c4c8d26e7.png">

3. Move header and description more up
<img width="898" alt="Screenshot at Dec 08 13-34-33" src="https://user-images.githubusercontent.com/7249484/145154092-d3b2989b-9820-4b42-8e2b-10937b406697.png">

4. Add Total transfered amount (to BEAM), Total transfered amount (to Ethereum) and Latest/Next transfer widgets.
([separate task](https://github.com/BeamMW/beam-bridge-ethapp/issues/7))

5. Add metamask logo
<img width="902" alt="Screenshot at Dec 08 13-34-19" src="https://user-images.githubusercontent.com/7249484/145154116-a672bfe1-a9dc-499d-9c7b-183358743773.png">

**Comment by beam-mw** [comment]
Older design. Irrelevant
