### ISSUE TITLE
Bridges. Send screen 

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/beam-bridge-ethapp#3]
This screen is part of the Ethereum to Beam flow (all flow is described here https://docs.google.com/document/d/1yYJ8SJzi-0gtBtbQnuzXik559WZIUfcxfl1FDduoFVo/edit)

The user gets to this screen in one of 3 ways, that described here https://zpl.io/2jKeDom
![bridges receive alternative](https://user-images.githubusercontent.com/7249484/145972847-081c6ea2-9950-4859-a6e1-607f3d69613f.png) or when pressing "Ethereum to Beam" button in the web side of the bridge.

**1. Automatic way (recommended)**
https://zpl.io/2yRMB8p

The user gets to this screen by pressing by following the link from the wallet. That way the user should see read-only address.
![bridges web send](https://user-images.githubusercontent.com/7249484/145001087-cb58f33c-e013-4c2c-9c69-bfa3a32d5375.png)

**2. Manual way**
https://zpl.io/2yRMB8p

The screen looks the same as in the previous point, but the user gets to this screen by copying and pasting link from wallet to web browser. That way the user should see a read-only address.
![bridges web send](https://user-images.githubusercontent.com/7249484/145001087-cb58f33c-e013-4c2c-9c69-bfa3a32d5375.png)

**3. Completely manual way**
https://zpl.io/bA3YrWB

<img width="472" alt="Screenshot at Dec 07 17-12-08" src="https://user-images.githubusercontent.com/7249484/145000472-b6e92981-8197-4b8d-84fe-f276f245527e.png"> 

The user gets to this screen by copying and pasting link to send screen from wallet to web browser or by pressing Ethereum to Beam button on the main web screen
<img width="945" alt="Screenshot at Dec 14 17-47-18" src="https://user-images.githubusercontent.com/7249484/145974194-c4194d19-fbfd-4e85-b62c-b621915b1947.png">

_Changes_
- Add currency icon in the input
- currency should be read only
<img width="472" alt="Screenshot at Dec 07 17-12-08" src="https://user-images.githubusercontent.com/7249484/145000472-b6e92981-8197-4b8d-84fe-f276f245527e.png">
- add address's network below the input field
<img width="437" alt="Screenshot at Dec 07 17-12-19" src="https://user-images.githubusercontent.com/7249484/145000487-c8216ec9-2d84-4649-8428-43c7bc51db8e.png">
- add Relayer fee and Expected ethereum network fee (read only)
<img width="440" alt="Screenshot at Dec 07 17-12-30" src="https://user-images.githubusercontent.com/7249484/145000501-f5c7bec6-2694-4eec-960b-17b5e6b0521c.png">
- rename Send button into Transfer
<img width="455" alt="Screenshot at Dec 07 17-12-41" src="https://user-images.githubusercontent.com/7249484/145000599-6f2bec68-9c55-4491-8ea3-7359e305dca7.png">

_Empty state_ 
https://zpl.io/bzzOyJz
- add "send" link gradient
- rename input field header into Bean bridge address
<img width="951" alt="Screenshot at Dec 07 17-08-51" src="https://user-images.githubusercontent.com/7249484/144999849-6923348d-bf3e-4766-a1eb-620b63c1be02.png">
- rename window header into Ethereum to Beam
<img width="948" alt="Screenshot at Dec 07 17-08-35" src="https://user-images.githubusercontent.com/7249484/144999824-88a10d94-c193-4456-bf15-5f147568830e.png">

The empty state has an input field for the address and the instruction. When user enters the address, there 3 ways what send window can become.

**Error state**
https://zpl.io/VK3YrDX

![bridges web send error](https://user-images.githubusercontent.com/7249484/144999909-4819ba4d-fd2a-45bb-8fc9-54c749b15279.png)

Note. If token is not approved, the approve token screen should be shown first, before screen above with the amount input field.
https://zpl.io/2yRMB8p
https://zpl.io/VqMRpY4

![bridges web send input approve](https://user-images.githubusercontent.com/7249484/145974672-ee5c7fdb-e95c-46c3-99d2-208915e0fe21.png)
![Uploading bridges web send approve.png…]()

**Comment by sinaizd** [comment]
checked
