### ISSUE TITLE
Bridges. Enable wallet disconnect

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/beam-bridge-ethapp#4]
https://zpl.io/bexGgWq
Profile "dialog" opens by click on the metamask address
<img width="938" alt="Screenshot at Dec 07 17-18-25" src="https://user-images.githubusercontent.com/7249484/145001421-9627730c-8da8-47ec-a814-d99716e57c41.png">

In the "profile" dialog there should be a possibility to revoke tokens (but only those which was approved before), except ETH token which is always approved by default.
![bridges web profile](https://user-images.githubusercontent.com/7249484/145001352-2e97cbf1-f6a5-4260-874f-fdf36f268101.png)

**Comment by sinaizd** [comment]
checked
