### ISSUE TITLE
Bridges. Receive screen 

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/beam-bridge-ethapp#5]
**_This screen is part of the Beam to Ethereum flow (all flow is described here https://docs.google.com/document/d/1yYJ8SJzi-0gtBtbQnuzXik559WZIUfcxfl1FDduoFVo/edit)_**

https://zpl.io/bA3wAXP

![bridges web receive](https://user-images.githubusercontent.com/7249484/144997938-65783802-7396-4744-8db6-1b5283fdba6a.png)

- User gets to this screen from the main website screen when presses Beam to Ethereum button
<img width="958" alt="Screenshot at Dec 14 17-28-13" src="https://user-images.githubusercontent.com/7249484/145971008-cb4dd20b-6e3c-472e-8896-ef4e1eb96096.png">
- User can leave the screen by pressing Back or Copy and close icon
- If user presses Copy and close, show toast notification on the main screen) https://zpl.io/VD3rwDq
<img width="380" alt="Screenshot 2021-12-14 at 17 26 11" src="https://user-images.githubusercontent.com/7249484/145970781-a0df3eab-2f80-46c9-bf66-35ecaeceddad.png">
- Download the latest version of Beam Wallet link should open https://beam.mw/downloads/mainnet

**Comment by sinaizd** [comment]
checked
