### ISSUE TITLE
Bridges. Main user screen. Relay info

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/beam-bridge-ethapp#6]
https://zpl.io/VDmEdpJ
Add My transferred (ethereum to beam/beam to ethereum) widgets
<img width="949" alt="Screenshot at Dec 07 16-50-02" src="https://user-images.githubusercontent.com/7249484/144997230-d5cf2300-d57c-4d0c-a882-394608a2a1f1.png">

**Comment by beam-mw** [comment]
Irrelevant.
