### ISSUE TITLE
Bridges. Main screen (before connecting wallet). Relay info

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/beam-bridge-ethapp#7]
https://zpl.io/awdoOlN
Add Total transfered amount (to BEAM), Total transfered amount (to Ethereum) and Latest/Next transfer sections.
<img width="905" alt="Screenshot at Dec 08 13-33-59" src="https://user-images.githubusercontent.com/7249484/145154156-fa591153-a12d-483f-9a92-2573264c2554.png">

The height of all 3 sections should be same and depends on sections, that has maximum amount of lines.
<img width="678" alt="Screenshot at Dec 08 13-34-50" src="https://user-images.githubusercontent.com/7249484/145154265-5fe96df5-6195-4685-990b-ef89d3e03807.png">

**Comment by beam-mw** [comment]
Older design. Irrelevant
